name: Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your default branch is named differently

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  convert-and-deploy:

    runs-on: ubuntu-latest
    environment:
      name: github-pages  # Name of the GitHub Pages environment

    steps:
    - uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir html
        for file in docs/*.md; do
          pandoc "$file" -o "html/${file##*/}.html"
        done

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4

    - name: Create GitHub Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4